from typing import Literal

from pydantic import BaseModel

AvatarGenerationStatus = Literal["waiting", "completed", "failed"]


class GenerateAvatarVideoRequest(BaseModel):
    project_id: str
    # Must already be a "audio" asset in this project -- e.g. the output of
    # POST /api/tts/synthesize. This app never sends raw text/script to the
    # avatar provider; narration audio is always generated by our own TTS
    # first, so the avatar is just a lip-synced visual layer on top of it,
    # not a second (paid) narration source.
    audio_asset_id: str
    # Falls back to settings.heygen_default_avatar_id when omitted -- no
    # avatar-picker UI exists yet (see AVATAR.md-equivalent note in
    # service.py), so every generation uses the one configured avatar until
    # that's built.
    avatar_id: str | None = None


class GenerateAvatarVideoResponse(BaseModel):
    id: str
    status: AvatarGenerationStatus


class AvatarGenerationDetail(BaseModel):
    id: str
    status: AvatarGenerationStatus
    asset_id: str | None = None
    url: str | None = None
    error: str | None = None


class AvatarOptionResponse(BaseModel):
    id: str
    name: str
    preview_image_url: str | None = None
    gender: str | None = None
    preferred_orientation: str | None = None


class AvatarOptionsResponse(BaseModel):
    avatars: list[AvatarOptionResponse]
